### ISSUE TITLE
Extension permission

### ISSUE THREAD

**Issue by alfredonodo** [alex-vv/page-load-time#29]
Hi,
I like your extension and I prefer it against [load time](https://addons.mozilla.org/en-US/firefox/addon/load-time/?src=search). However, why does it requires _Access your data for all web sites_ while load time does not require any permission?
Thank

**Comment by alex-vv** [comment]
This is because that load time extension only shows page load time information when you click on its icon. Until user initiate this action data is not available. That is because it uses "activeTab" permission only:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activeTab_permission

In my extension load time is available right away without user interaction. To do that I need to inject content script which measures load time for any website you visit. So far I could not find a way to do it without a permissions warning.
