### ISSUE TITLE
Incorrect position of the load numbers indicator

### ISSUE THREAD

**Issue by gitti0** [alex-vv/page-load-time#34]
There is incorrect position of the load numbers indicator in Firefox. That's easily can be seen if you load a page, where the time is consisting of 4 numbers.

I have Firefox 78.7.1 ESR and Page-Load-Time 3.2.0

![FF_numbers](https://user-images.githubusercontent.com/72917708/107235917-15f67000-6a1d-11eb-9079-127d20e66c38.jpg)

**Comment by alex-vv** [comment]
Thanks, fixed in 3.2.1

**Comment by gitti0** [comment]
@alex-vv, the number box in Firefox is not in the center of the icon, like is in Chrome. I see the max numbers, which can be fitted in the indicator box are like in 3.2.0 - 4 and in 3.2.1 - 3.

Do you think, there is a way in which we can make Firefox like Chrome? The number box to be in the center of the icon.

![plt321](https://user-images.githubusercontent.com/72917708/107381102-6d144780-6ae6-11eb-8eff-19036164f5b1.jpg)

**Comment by alex-vv** [comment]
No, unfortunately I cannot control the badge position. I think all Firefox extensions show this badge in the same way. In version `3.2.1` I fixed the problem with trimming numbers. Since there was not enough space `12.85` was trimmed, now it will be shown as `12.9`, but I cannot change the position.
